### ISSUE TITLE
상품 등록 페이지 수정

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#101]
- 필수값 유효성검사 추가
- 에디터 최종 수정 (사진 플러그인 없음 / 풀버전)

**Comment by du-sel** [comment]
- 파일 받는 input 추가

**Comment by du-sel** [comment]
- 할인여부 토글슬라이드 부분 사이드바랑 충돌하지 않게 수정?

**Comment by jaeeun25** [comment]
오오 너무 좋아용!
아 상품 관리 페이지에서 대표 상품 등록&신규 상품 등록 버튼을 쬐끔 모서리를 둥글게 하는게 좋지않을까용..?

**Comment by du-sel** [comment]
오 수정했습니다 !!

**Comment by jaeeun25** [comment]
오..! 근데 제가 파일을 잘못 올려서 코드가 사라진걸까요..? 풀했는데 제 화면에서는 아직 반영이 안되어있어서욥..ㅜㅜ

**Comment by du-sel** [comment]
헉... 제가 다시 올려볼게요..!

**Comment by jaeeun25** [comment]
옹! 확인했습니다~
