### ISSUE TITLE
마이스토어 - 스토어관리 수정

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#102]

**Comment by du-sel** [comment]
유효성검사에서 나오는 초록색 글씨도 컬러파레트 상의 색상으로 바꾸면 어떨까요?!  (5번 색상?)
너무 눈에 안띄어서 일부러 다른 색을 쓰신 걸까요??

**Comment by jaeeun25** [comment]
오 일부러 다른 색을 썼다기보다는 처음에 컬러 정하기 전에 대부분 유효성 검사 텍스트 색이 초록/빨강인거같아서 그렇게 일단 잡고 진행했어요! 그럼 일단 5번 색상으로 바꾸고 다시 올릴게요!

**Comment by du-sel** [comment]
오오엉 전 지금 바꾸신게 좋은거같아요!!
저는 다른 피드백은 더 없읍니당ㅎㅎ
