### ISSUE TITLE
커뮤니티 인풋창 수정

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#104]
- 닉네임 아래 border 삭제
- 인풋창 열리는 아이콘(버튼) +로 수정
- 업로드 가능한 파일 4개로 제한

**Comment by hje00928** [comment]
포스트 작성할 때 업로드 사진 개수 제한 걸어야 될까요?

**Comment by jaeeun25** [comment]
최대 2-3개가 좋지않을까용?

**Comment by du-sel** [comment]
- 지금은 사진이 여러개 올라갈 수 있는건가욥?!
저는 제한을 건다면 한 4개 정도로 생각했어요 ㅎㅎ 짝수가 배치하기 편할 것 같아서...
- 그 프로필이랑 닉네임 나오는 부분 아래의 border 을 그냥 없애도 될 것 같아요..! 지금 포스트 박스에도 해당 보더가 없어서 둘을 맞추는게 낫지 않을까 싶네요
- 그 input창이 펼쳐지게 만드는 버튼이랑 실제로 글을 등록하는 버튼이랑 좀더 다르게 생긴게 좋을 것같아요..! 펼쳐지게 만드는 아이콘을 그냥 플러스모양(+) 으로 하는 것도 괜찮을 것 같아요

**Comment by du-sel** [comment]
확인했습니당!! 👏👏
