### ISSUE TITLE
커뮤니티 사이드바 수정

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#105]

**Comment by du-sel** [comment]
1)
메뉴 이름을

- 통합 피드
- 팔로잉 피드
- 크리에이터 피드

- 내가 댓글 남긴 포스트
- 내가 좋아요한 포스트

이런 식으로 바꾸는건 어떨까요?
(포스트 한개는 포스트, 포스트를 모아서 보는 화면은 피드라고 생각했는데 그냥 전부 포스트로 통일하는게 나을까요?)



2)
위의 3개 / 아래 2개 사이에 좀더 간격이 들어갔으면 좋겠다는 생각이 듭니당 ㅎㅎ

**Comment by du-sel** [comment]
색상은 제가 조금 수정했습니다!!

**Comment by du-sel** [comment]
모바일버전 짱입니다👍

**Comment by jaeeun25** [comment]
오 생각해보니까 포스트랑 피드는 다르네요! 하나로 통일하면 좋을거 같긴한데 포스트라고 했을 때 모아보는 화면을 뭐라하면 좋을지..ㅎㅎ 일단 그럼 얘기하신 대로 수정하고 다시 올리겠습니다!

**Comment by du-sel** [comment]
오왕 저는 이것도 수정버전 다 좋습니다!!
