### ISSUE TITLE
커뮤니티 포스트 수정

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#106]
- [x] 본문 텍스트 5줄 이상 넘어가면 쩜쩜쩜(...) 처리
- [x] 포스트 하단에 표시될 내용은 댓글개수 / 댓글쓰기버튼 / 좋아요버튼
- [x] 피드보기 상태일때는(=포스트 상세조회가 아닐때는) 댓글 내용은 보이지 않고 댓글개수만 표시됨
- [x] 댓글쓰기 버튼을 누르면 그 아래로 댓글입력 input과 버튼 있는 부분이 펼쳐짐
- [x] 포스트 박스부분 클릭시 포스트 상세조회 페이지로 연결

**Comment by du-sel** [comment]
와앙 고생하셨어요~~!!

- "포스트 박스부분 클릭시 포스트 상세조회 페이지로 연결"
이 부분의 경우 포스트 이미지 부분이 아니라 전체 박스 아무데나 클릭해도 포스트 상세페이지로 넘어가게 수정해주시면 됩니다!

- 그래서 본문의 더보기 처리도 그냥 상세페이지로 넘어가면 보이는 것으로 처리하면 될 것 같습니당

- 하단의 댓글개수 부분을 클릭하면 새로고침이 되면서 댓글 input 창이 생기는데 혹시 일부러 넣으신 건가용...?! 
댓글쓰기 버튼이 따로 있으니까 이부분에는 onclick 효과는 없어도 될 것 같아요!

- 포스트 이미지의 비율은 원래 저런게 아닌데 찌그러져서 보이는거겠..죠?
background-image --> background-image: cover 처리하거나 overflow: hidden 처리하셔서 비율이 안맞는 이미지가 들어와도 찌그러지거나 늘어지지 않게 해주시면 좋을 것 같습니당

**Comment by du-sel** [comment]
- 아 포스트 박스 하단의 3번컬러 배경색은 없어도 될 것 같아요..! 뭔가 전부 하얀색으로 통일되는게 깔끔하지 않을까 싶네요

**Comment by hje00928** [comment]
포스트 하단 배경색 없앴습니다~

**Comment by du-sel** [comment]
네 하단 확인했습니다!

**Comment by du-sel** [comment]
그 윗댓글에 있는 내용은 아직 반영 안된 것 같은데 맞나요??

**Comment by hje00928** [comment]
네 피드백 수정 중 입니다~
