### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by jaeeun25** [du-sel/teamproject#123]

**Comment by jaeeun25** [comment]
구글 드라이브에 erd 파일이랑 캡처한 이미지, 컬럼 상세 정보 정리한 엑셀 파일 올려뒀습니다!

**Comment by du-sel** [comment]
확인했습니다! 짱이에용👍

**Comment by jaeeun25** [comment]
앗 넵넵 혹시 그럼 mysql erd 파일도 같이 수정하신 건가용?

**Comment by du-sel** [comment]
앗 아뇨 mysql은 아직 수정 안했어요...!

**Comment by jaeeun25** [comment]
그럼 제가 수정해서 다시 올릴게용~

**Comment by du-sel** [comment]
엌 제가 방금 수정했...는데 저희 이렇게 엇갈리는걸까요 ㅋ크ㅜㅡㅜ

**Comment by jaeeun25** [comment]
엌ㅋㅋㅋㅋㅋㅋㅋㅋ 방금 열었다가 확인햇어욬ㅋㅋㅋ

**Comment by du-sel** [comment]
구글시트 "테이블설계"에 댓글 남겨놓았습니다!

https://docs.google.com/spreadsheets/d/1JfTiywFmVd-HCxz2VE_7cVyuzOxddiyBTlVGxcMjcJ0/edit#gid=0

**Comment by jaeeun25** [comment]
- [ ]다운로드 링크 백업 테이블 추가
