### ISSUE TITLE
상단 탭 current값 주기

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#126]
커뮤니티에 있을때는 커뮤니티 쪽이 active 되도록 처리

**Comment by jaeeun25** [comment]
co-main, post말고 커뮤니티 탭이 활성화돼야하는 페이지가 또 있을까요
화면설계에 보면 회원 정보 수정도 커뮤니티 쪽으로 되어있긴한데..

**Comment by du-sel** [comment]
커뮤니티 피드(메인) / 커뮤니티 포스트 / 프로필 / 회원정보 수정
이렇게입니다!

**Comment by du-sel** [comment]
혹시 지금 올라와있는 버전이 active 적용이 되어있는 상태인가요?!
지금 pull 받아본걸로는 아직 안되어 있는 것 같아서요..!

**Comment by jaeeun25** [comment]
co-main, post 페이지에서는 커뮤니티에 active 되어있고 나머지는 스토어가 active 적용되어 있는거면 맞아용..! 일단 프로필이랑 회원정보도 커뮤니티로 해서 다시 올려볼게욥..!

**Comment by jaeeun25** [comment]
혹시 제가 잘못 이해하고 있는걸까용..? 커뮤니티 관련 페이지면 커뮤니티 탭이 활성화되고 색상이 커뮤니티 색상으로 변경되면 되는거 맞나욥

**Comment by du-sel** [comment]
넵넵 그게 맞는데 지금 저의 화면에서는 양쪽다 이렇게 보여요...!

![Image](https://github.com/du-sel/teamproject/assets/111416908/8872a018-4ae3-498f-9645-ad1ad3f719d1)

**Comment by du-sel** [comment]
Q. 회원정보나 프로필은 그럼 헤더 색상이랑 맞춰서 탭을 흰색으로 해야하나요..?

> 넵넵 여기는 흰색으로 맞추는게 좋을 것 같아요!..... 귀찮은게 많네요 진짜 ㅋ  ㅋ

**Comment by jaeeun25** [comment]
므엥..일단 다시 올렸어요!
