### ISSUE TITLE
DB 트리거 추가

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#207]
- [x] 상품 업로드시 상품백업 테이블에도 업로드
- [x] 구독시 팔로우 테이블에도 업로드
- 더 있나요...?!
---
추가 하시는 분은 그부분 SQL만 복사해서 공유해주세요 :)

**Comment by hje00928** [comment]
-- post 삭제 전 comment 삭제 트리거 생성
delimiter $$ 
	create trigger before_post_delete before delete
		on post
        for each row
        begin
			delete from comment where post_id = old.post_id; 
        end $$
delimiter ;

**Comment by jaeeun25** [comment]
혹시 cascade 반영한 이후에도 comment가 삭제가 안되는 건가요?
