### ISSUE TITLE
프로필 - 프로필사진/배경사진

### ISSUE THREAD

**Issue by du-sel** [du-sel/teamproject#352]
- [x] 사진 추가
- [x] 모달창 수정사항 (이전 이슈 참고)
- [x] 사진 수정

**Comment by jaeeun25** [comment]
기존에 생성한 계정들은 프로필이랑 배경 이미지에 디폴트 값이 없어서 아마 업로드 하시면 에러가 발생하실거에용!

새로 생성한 계정으로 테스트해보시거나 디비에 각각 아래 값들 넣어서 테스트해보시면 됩니다!
프로필 - /resources/profilefile/profile/basic-profile.png
배경 - /resources/profilefile/background/basic-background.png

**Comment by du-sel** [comment]
오 확인했습니다!
