### ISSUE TITLE
스크롤, 구독 등 자잘한 수정

### ISSUE THREAD

**Issue by jaeeun25** [du-sel/teamproject#492]
- [x] 모바일 메뉴 가로 스크롤 삭제
- [x] 구독 수정 버튼 조정
- [x] 리뷰 판매자 답글 html
- [x] 크리에이터 목록에서 스토어, 대표상품 글씨 크기 서로 변경
- [x] 문의 제목 필수 걸어놓기
- [x] 스토어 개설한 경우 스토어네임 프로필에 뜨도록 - 채원이가 한대용><
- [x] 구독 트리거 바꾸기(팔로우 있는경우 insert 안되도록)

**Comment by jaeeun25** [comment]
제 노트북에서는 가로 스크롤이 아예 안떠서 확인이 불가능합니다ㅜㅜ 혹시 확인가능하시면 잘 적용됐는지 확인 부탁드립니다!

**Comment by jaeeun25** [comment]
트리거 삭제 후 java코드로 수정했습니다

**Comment by du-sel** [comment]
오 모바일 가로스크롤 안나옵니다!!
